dynamic_rest/serializers.py

Fix a few `getattr` related bugs.

Add default values for getattr

---

dynamic_rest/serializers.py
tests/test_api.py

Add simple flag (`exclude_links`) to exclude links on a per-request basis.

[Feature] Exclude `links` on a per-request basis

---

benchmarks/test_bench.py

xrange doesn't exist in python 3

Fixed python 3 compatibility

---

dynamic_rest/routers.py
tests/test_viewsets.py

This is to enable bulk PATCH requests, without this PATCH not allowed.

Add patch to list route

---

README.md
README.rst
dynamic_rest/filters.py
tox.ini

Adds Django REST Framework 3.5.x compatibility

---

dynamic_rest/viewsets.py
tests/test_viewsets.py

Adds CSV import support to viewsets that support bulk creation
TODO:

working CSV upload support

---

dynamic_rest/fields/fields.py

@ryochiji related to https://altschool.atlassian.net/browse/ALTOS-13793

Make error handling more robust, if debug isnt an attribute

---

dynamic_rest/client/query.py
dynamic_rest/utils.py
install_requires.txt
tests/test_client.py

Addressing https://github.com/AltSchool/dynamic-rest/issues/152 and fixing integration test which triggers this issue

add six to dependencies to fix integration

---

README.md
dynamic_rest/viewsets.py

https://github.com/AltSchool/dynamic-rest/issues/177 remove overriding of DRF renderer settings

https://github.com/AltSchool/dynamic-rest/issues/177

---

circle.yml

Update python versions to available on Cicle

#182 Update circleCI config

---

dynamic_rest/fields/fields.py
dynamic_rest/filters.py
dynamic_rest/prefetch.py
dynamic_rest/serializers.py

Fixes prefetch logic on the slowquery side, and updates validation for related fields.
Also fixes a merge regression.

[FastQuery] Fix Prefetches and field validation

---

dynamic_rest/filters.py
setup.py
tests/test_api.py

Rebasing @Incanus3's commit from #171.
https://github.com/AltSchool/dynamic-rest/compare/master...Incanus3:feature/ordering-by-related-fields
https://github.com/AltSchool/dynamic-rest/compare/d564cd10437cbd136db68a514481da29fd2a5ae7...master#diff-fbc210b7daea111dceb4ac7cec923baf

Add support for ordering by nested fields #171

---

dynamic_rest/processors.py
dynamic_rest/serializers.py
requirements.test.txt
requirements.txt
tests/test_serializers.py

Add support for post processors that run as the last step in serialization (i.e. after SideloadingProcessor).

add post processor support

---

dynamic_rest/serializers.py

Change caused test failures. Reverting.
Reverts AltSchool/dynamic-rest#233

Revert "Update DynamicListSerializer"

---

dynamic_rest/filters.py
dynamic_rest/serializers.py

Eliminate some unnecessary queries in the PATCH flow.

fix couple of inefficiencies in POST/PATCH flows

---

README.md

Make explicit how to sort in descending order

---

setup.py

New changes:
- Added patch-all support to `DynamicModelViewSet`, allowing many records selected by a query to be updated with a single PATCH request

bump to 1.9.3

---

dynamic_rest/prefetch.py

Avoid key error by checking for existence before using the key.
fixes https://altschool.atlassian.net/browse/ALTOS-18912

Added check to avoid keyError

---

install_requires.txt

see #300 and #301 
closed #301 when merged

upgrade inflection to 0.4.0

---

dynamic_rest/datastructures.py
dynamic_rest/fields/fields.py
dynamic_rest/filters.py
dynamic_rest/links.py
dynamic_rest/processors.py
dynamic_rest/routers.py
dynamic_rest/serializers.py
dynamic_rest/utils.py
dynamic_rest/viewsets.py
install_requires.txt
requirements.txt
tests/test_api.py
tests/test_serializers.py

I went through and replaced `from django.utils import six` with `import six` I think There still needs to be some polishing up done in the requirements files etc.

Compatibility with Django 3

---

.circleci/config.yml
.github/workflows/test.yml
README.md
install_requires.txt
requirements.benchmark.txt
setup.py

Regarding [issue 332](https://github.com/AltSchool/dynamic-rest/issues/332)

Loosening and updating oddly specific minor version requirement in install requires

---

.github/workflows/test.yml
install_requires.txt
setup.py
tox.ini

Drop django 2.2
Drop support for drf 3.11, 3.12
Add support for drf 3.15
Add support for py 3.11

drop support for dj2, dj3.1, drf311, drf312. add support for drf315, py311
