AltSchool/dynamic-rest

dynamic_rest/filters.py

The current approach of deciding when to use `.distinct()` can result in prefetch queries returning multiple rows of the same object (current known example is on a many-to-many field through a join table). This change forces all prefetch queries to use `.distinct()` (which is probably a bit ham-fisted, but should also be safe and low-impact).
See #ALTOS-5703

always use distinct() on prefetch queries

---

.isort.cfg
dynamic_rest/conf.py
dynamic_rest/fields.py
install_requires.txt
tests/test_serializers.py

Reverts AltSchool/dynamic-rest#72

Revert "global serializer cache"

---

dynamic_rest/meta.py
dynamic_rest/routers.py
dynamic_rest/serializers.py
tests/test_router.py
tests/urls.py

This PR adds a new `router.register_resource()` API for registering the canonical resource URL. It automatically generates the path using the viewset's serializer's resource name to enforce our existing naming convention. The router then internally maintains a reverse map so we can take a resource name and generate a URL with confidence, as well as determine a resource's canonical serializer.
TODO:

new router API to allow DREST to map/generate canonical resource URLs

---

README.md
dynamic_rest/conf.py
dynamic_rest/processors.py
tests/test_api.py

Makes the configurable. Using `_` instead of `+` matches what Ember expects for "additional sideloaded primary resources", and should allow it to use its magic. However, for backwards compatibility, the default will remain `+`

Make the prefix for additional primary resources configurable

---

dynamic_rest/fields/generic.py
dynamic_rest/routers.py
tests/serializers.py
tests/test_generic.py

Follows up on #94, adding the ability to put/patch against a polymorphic field.
I'll be following up with some additional testing, as I'm only currently testing the `PATCH` case.
Depends on #94 
Note that this also changes the assumption around the `_type` properties... Now, they're the singular version of the name, not the plural.

Feature: DynamicGenericRelationField write flows

---

dynamic_rest/serializers.py
tests/serializers.py
tests/test_api.py
tests/test_serializers.py

Adds a flag to the serializer's Meta that allows any serializer to override the global setting `DEFER_MANY_RELATIONS`

Add serializer meta flag for deferring m2m by default or not

---

README.md
dynamic_rest/conf.py
dynamic_rest/links.py
tests/test_api.py

Not a whole lot to this one.  Adds a setting to allow us to set the default `link` format to be host-relative URLs.
Note that in order for these links to be effectively generated, the primary resource must be registered with DynamicRouter.  If the resource isn't registered with DynamicRouter, all `links` generated will default back to resource-relative URLs.
This does change the base behavior of links; instead of namespace-relative urls (that were technically invalid URLs), the default behavior is now a proper URL (host-relative or resource-relative), in both cases.

Make resource vs host-relative links urls configurable.

---

dynamic_rest/serializers.py

The `get_link_fields` method was calling `field.serializer`, causing serializers to be constructed, which turns out to be very expensive. This PR uses alternative means of accomplishing the same logic that don't require serializers to be constructed. (In one API hitting 4 resources, this resulted in a ~25% reduction in CPU usage.)
Before (blue boxes show serializer construction caused by `get_link_fields`):
After:

link field performance optimization

---

dynamic_rest/fields/generic.py
tests/test_generic.py

There was a bug in GenericForeignKeyField's `id_only()` method where it was erroneously returning `False` if the field was being included by default (and therefore didn't have a key in `request_fields`). This PR fixes the bug by using the new `.is_field_sideloaded()` method (i.e. `id_only` is true if the field isn't being sideloaded).

fix bug in GenericFKField

---

dynamic_rest/viewsets.py
tests/test_viewsets.py

Fixes bug in bulk-creation where sideloads are returned nested, instead of pulled out under top-level keys. This was happening because the response wasn't being passed through `SideloadingProcessor`.

fix bulk-creation sideloading bug

---

dynamic_rest/serializers.py
tests/serializers.py
tests/test_api.py

DRF automatically trims whitespace on CharFields.  This can be turned off by setting the flag to False on that field.   This PR adds a Meta parameter for overriding this flag.

Support Meta.preserve_whitespace fields list

---

.isort.cfg
CONTRIBUTING.md
requirements.txt
runtests.py

`isort` tests that module imports are sorted in alphabetical order within system, 3rd party, and 1st party blocks.
Unfortunately, it seems to be somewhat flaky in its detection of 3rd party vs 1st party packages, to the extent that it produces inconsistent results between local testing and CircleCI testing, and even between different runs of the same code on CircleCI (??).
As such, we have decided to remove it and rely exclusively on flake8 for linting.

Remove isort testing

---

.gitignore
README.md
dynamic_rest/meta.py
tox.ini

Fix get_field_by_name, get_all_related_objects, get_all_related_many_to_many_objects for Django >= 1.10

Support Django >= 1.10

---

dynamic_rest/filters.py
dynamic_rest/viewsets.py

When using `.only` on querysets, the objects returned aren't actually instances of the model, but derived instances of the class that signify that certain fields are deferred.  This causes certain signals to not be fired, since we typically wire these up by way of `post_save` or `post_delete` hooks, connected with a particular model class as a sender.
Since django apparently strictly matches the model being acted on to the sender passed in through the `@receiver` decorator or `.connect` (i.e. `@receiver(post_delete, sender=FooModel)`), this causes models with deferred fields to not invoke the proper signal handlers.
See this [stack overflow answer](See http://stackoverflow.com/questions/35006328/post-delete-pre-delete-signals-not-firing-for-specific-sender) for more details.
This fix …

Exclude delete requests from having fields deferred

---

dynamic_rest/viewsets.py
tests/test_viewsets.py

We don't want to return 405's in all situations, only when we weren't able to retrieve the primary key. `get_object` could fail even if we have the primary key, for example if `filter_queryset` excludes the object.

Only return 405 on AssertionError (unable to retrieve pk)

---

dynamic_rest/fields/fields.py
tests/test_api.py

1. Repairs broken code introduced in #142 .
2. Alters unit tests to be more flexible regarding nullability of inverse fields. There's precedent for this; we believe that the `get_model_field` upgrade actually uncovers a bug that was previously masked.

fix bug where model field lacks args

---

dynamic_rest/filters.py
dynamic_rest/meta.py
tests/test_viewsets.py

During our Django upgrade work, we noticed that nested prefetches which worked in Django 1.9/1.8/1.7 are now misbehaving in Django 1.10.
This only applies to nested prefetch objects that use a queryset which itself prefetches a distant relationship using the original `a__b` prefetch syntax.
For example, the following query fails in Django 1.10 but works in earlier versions:
```
A.objects.all().prefetch_related(
Prefetch(
'b',
queryset=B.objects.all().prefetch_related(
'c__d'
)
)
)
```
However, if we change the internal prefetch of `c__d` to use the fully-nested syntax, all is well in Django 1.10:
```
A.objects.all().prefetch_related(
Prefetch(
'b',
queryset=B.objects.all().prefetch_related(
Prefetch(
'c',
queryset=C.objects.all().prefetch_related(
'd'
)
)
)
)
)
```
TODOs:

attempt to fix 1.10 prefetch a__b nested issue

---

dynamic_rest/viewsets.py
install_requires.txt
tests/serializers.py
tests/test_serializers.py

We currently use Django 1.10.3 and djangorestframework 3.5.2 with dynamic-rest. These versions fall outside the range allowed by dynamic-rest's install_requires.txt. We loosen the version requirements here to match real world usage.
It appears that this PR changes the tox tests. We never actually tested DRF 3.5 previously. E.g. notice ```djangorestframework==3.4.0``` in snippet of tox test logs:
```
py27-django110-drf35 create: /home/ubuntu/dynamic-rest/.tox/py27-django110-drf35
py27-django110-drf35 installdeps: Django==1.10.0, djangorestframework==3.5.0, -rrequirements.txt
py27-django110-drf35 inst: /home/ubuntu/dynamic-rest/.tox/dist/dynamic-rest-1.6.2.zip
py27-django110-drf35 installed: alabaster==0.7.9,appdirs==1.4.2,Babel==2.3.4,baron==0.6.5,click==6.7,cov-core==1.15.0,coverage==3.7.1 …
```

Loosen version requirements to match real world usage

---

dynamic_rest/serializers.py

The way that `DynamicModelSerializer` is currently written it is not possible to define a custom `list_serializer_class`, as that attribute is overridden in the `__new__` method. Provided that the user-defined `list_serializer_class` extends `DynamicListSerializer`, it should be settable.

Allow setting Meta.list_serializer_class

---

dynamic_rest/viewsets.py

Given that `get_queryset` returns a configurable queryset, we may end up with an edge case where the same model is returned multiple times.
Ensure that the set is distinct before attempting to delete models, to prevent issues around trying to delete a model multiple times.

Ensure models aren't deleted multiple times

---

dynamic_rest/fields/generic.py

clients can override this if desired (to mock a generic relation, for
example)
Because we're pushing everything to `StudentCard`, in v4 API we still want `v4/evidences/?include[]=content_object.` to sideload using the correct serializer. In vishnu-backend we override the method provided here to accomplish that. https://github.com/AltSchool/vishnu-backend/pull/4046

Add a method for getting the serializer from an instance, so that

---

docs/conf.py

I don't know about the setup you guys are using, but if I clone a fresh copy of dynamic-rest and run `make docs` you get a `ModuleNotFoundError: No module named 'tests.settings'`. This PR fixes that by adding the relative path to the dynamic-rest project to sys.path in sphinx's `conf.py`

Fixed sphinx's python path

---

dynamic_rest/viewsets.py

https://github.com/AltSchool/dynamic-rest/issues/177
tox failed because flake8 lint detected obsolete import commands that I forgot to delete. Sorry 'bout that...

remove obsolete imports

---

circle.yml

Because of circle randomly change version of python on their build images, 
`pyenv install -s` install required python version implicitly if not available

#182 Update circleCI config install missing python versions

---

docs/tutorial.rst

Add import statement for WithDynamicModelSerializerMixin
The example for DREST-ifying Existing Serializer does not have an import statment. 
New developers with the package would have to lookup the module for WithDynamicModelSerializerMixin.

Add import statement

---

dynamic_rest/processors.py

My last pull request: https://github.com/AltSchool/dynamic-rest/pull/187
contains small bug when you try sideload the same object as primary resource as ADDITIONAL_PRIMARY_RESOURCE. 
https://cl.ly/3D3N0J2q1z0U

Fix sideloading ADDITIONAL_PRIMARY_RESOURCE

---

install_requires.txt
requirements.txt
tests/settings.py

includes Django 2.0 which requires python 3. DRF 3.6.4 fails on tests
currently so pin that as well
django-debug-toolbar: https://github.com/jazzband/django-debug-toolbar/blob/1.7/setup.py#L18, and Django 2.0 was released Dec 2017 which is why we didn't see this until now.
Also DRF 3.6.4 causes this repo to fail on one test:
```
tests/test_api.py:1507: in test_get_list
response = self.client.get('/users/?format=api')
build/lib/python2.7/site-packages/djangorestframework-3.6.4-py2.7.egg/rest_framework/test.py:282: in get
response = super(APIClient, self).get(path, data=data, **extra)
build/lib/python2.7/site-packages/djangorestframework-3.6.4-py2.7.egg/rest_framework/test.py:208: in get
return self.generic('GET', path, **r)
build/lib/python2.7/site-packages/django/test/client.py:416: in …
```

Fix failing builds: django-debug-toolbar specifies Django>=1.8, which

---

Makefile
dynamic_rest/filters.py
dynamic_rest/viewsets.py
tests/test_api.py
tests/urls.py
tests/viewsets.py

Django feature: https://code.djangoproject.com/ticket/18437
The issue is that these two querysets are not the same: 
`MasterCard.objects.filter(student_cards__is_archived=False).filter(student_cards__creator=<>)`
`MasterCard.objects.filter(student_cards__is_archived=False, student_cards__creator=<>)`
In the former, the `student_card` table is joined to `master_card` twice, and each join is filtered, whereas in the latter, `student_card` is joined once.
DREST takes all standard drest filters and wraps them into a single `filter` call, but adding custom filters outside of DREST ends up being a separate `filter` call, making it easy to run into this issue.
I've run into this a few times and thought it would make sense to allow callers a way to add filters into the DREST `filter` call, thus …

Allow view to inject additional filters in such a way that avoids this

---

dynamic_rest/prefetch.py
dynamic_rest/serializers.py

Adds compatibility with `DynamicGenericRelationField`, which provides no queryset to `Prefetch`

[FastQuery] Support for DynamicGenericRelationField

---

dynamic_rest/prefetch.py

Use `pk.attname` instead of `pk.name`, since `attname` resolves to the actual column name (and hence the right key for the `dict` representation of the model)

[FastQuery] Use proper pk attribute names

---

dynamic_rest/fields/fields.py
dynamic_rest/prefetch.py

Make things more consistent across `get_attribute` and `to_representation`, to avoid madness where `instance` is sometimes an instance, and sometimes the related model.

Try fixing some prefetch stuffs

---

dynamic_rest/serializers.py

In `DynamicSerializer._dynamic_init()` (which gets called every time a `DynamicModelSerializer` gets instantiated), there's a call to `field.get_all_fields()` that gets called even when not necessary (e.g. cases where the serializer is in `id_only` mode and we don't need to know about other fields). This PR moves the slow line to the cases where it's actually needed. See profiler output below:
**Before**
**After**

only fetch all fields in DynamicSerializer._dynamic_init() if needed

---

circle.yml
tox.ini

Tox tests for python 3.6 are failing on Circle. Remove for now.

fix circle builds

---

dynamic_rest/conf.py
dynamic_rest/serializers.py

Allow the list serializer class to be overridden globally. This makes it easier to override how the final data is [formatted](https://github.com/AltSchool/dynamic-rest/blob/master/dynamic_rest/serializers.py#L86), or otherwise transform the data once it has been aggregated.

allow list serializer class to be overridden globally

---

dynamic_rest/conf.py
dynamic_rest/serializers.py

Currently, we potentially serialize the same object over and over again when the same object instance appears many times (usually as sideloads).
For example, consider:
`/objectives/?include[]=subject.&include[]=rubric.rubric_items.`
There are actually only a handful of distinct subjects and a couple of sets of rubric/rubric items, but we re-serialize the subjects and rubrics for each objective. This PR introduces a cache that is tied to a specific serializer instance (which is shared within a single request context) to prevent such redundant serializations. (For that specific example above in our backend, this change reduces CPU usage by about half.)

cache serialized objects within a single context

---

requirements.benchmark.txt

Django 1.11.8 & 1.11.9 had a security vulnerability, and github decided
it wasn't happy with us not excluding these versions from
requirements.benchmark.txt, so in order to silence that warning, we are excluding those versions. I used version 1.11.15 as the lower version because that's what we're currently using in `vishnu-backedn`. This is used only when running benchmarks, so the main purpose of this PR is to silence the github warning.

Silence a github warning of a security vulnerability

---

dynamic_rest/filters.py

There was a bug in how we built [implicit prefetches](https://github.com/AltSchool/dynamic-rest/blob/33eba354857720ea6489b5481570a298442b3257/dynamic_rest/filters.py#L327) with FastQuery enabled, where for nested prefetches (i.e. prefetches that themselves have prefetches) the first layer was a [Django QuerySet](https://github.com/AltSchool/dynamic-rest/blob/33eba354857720ea6489b5481570a298442b3257/dynamic_rest/filters.py#L358) but then we were [adding FastPrefetch](https://github.com/AltSchool/dynamic-rest/blob/33eba354857720ea6489b5481570a298442b3257/dynamic_rest/filters.py#L348) objects to them (turns out Django's `QuerySet.prefetch_related()` [doesn't do any validation](https://github.com/django/django/blob/stable/1.11.x/django/db/models/query.py#L901)). That caused QuerySet …

Fix FastQuery implicit prefetch bug

---

dynamic_rest/routers.py
tests/test_router.py

Right now it's doing a shallow copy of the routes and hence your monkeypatch affects the source of the data. This causes all routes to accept `PATCH` and `DETELE` requests which in turn causes this exception instead of returning a 405:
> AssertionError: Expected view {viewset} to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.

Leave rest_framework router is unmodified

---

docs/dynamic_rest.html
dynamic_rest/filters.py

Hi, I have added 'iexact' to the list of available filters. 
https://docs.djangoproject.com/en/2.1/ref/models/querysets/#iexact

Add 'iexact' to available filters

---

dynamic_rest/filters.py
tests/test_api.py

When sorting by a related many-field, we need to call `distinct()` in order to remove duplicates

[ALTOS-22468] add fix for sort by relation

---

setup.py

https://github.com/AltSchool/dynamic-rest/pull/303 would cause this lib to break for people using py2, so bump the major version number prior to releasing

bump major version number since dropping py2 is a breaking change

---

Makefile
requirements.txt

Remove registration commands from makefile, as pre-registration is no longer required and the pypi api no longer supports it

Use twine to upload packages to pypi and test pypi.

---

dynamic_rest/conf.py
dynamic_rest/pagination.py
dynamic_rest/paginator.py
setup.py
tests/test_api.py

...to support a faster page-number pagination over large datasets
- Like standard `PageNumberPagination`, except the results are never counted
- Uses the N+1 trick from `CursorPagination` to determine whether the dataset has more pages
- Can be enabled on any request via query parameter `exclude_count` (name can be configured)
TODO:

add new "exclude count" page number pagination option

---

dynamic_rest/filters.py
install_requires.txt
requirements.benchmark.txt
tox.ini

- Django 4.2
- NullBooleanField deprecated in [DRF 3.14.0](https://github.com/encode/django-rest-framework/pull/8599)

Django 4.2 support
